#!/usr/bin/env node
// experience-context CLI — .experience.json -> <out>/CLAUDE.md (deterministik). Kod üretmez, app çalıştırmaz.
// spec-context'in frontend kardeşi. Bozuk/şema-dışı girdi -> exit 1, HİÇBİR ŞEY yazmaz (gate-before-write).
// Header'sız (insan-yazımı) CLAUDE.md -> exit 3, ezmez (--force ile ez). --selftest saf CLI kabul testleri.
import { readFileSync, writeFileSync, mkdirSync, existsSync, mkdtempSync, rmSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { extractObligations, renderClaudeMd, provenanceHeader, sha256, TOOL_STAMP } from './lib.mjs';

const HEADER_MARK = 'GENERATED by experience-context';

function usage() {
  console.error(`Kullanım: node experience-context.mjs <experience.json> --out <dizin> [--quiet] [--force]
          node experience-context.mjs --version
          node experience-context.mjs --selftest

  <experience.json>  Frontend Analiz emit çıktısı (.experience.json)
  --out <dizin>      CLAUDE.md yazılacak dizin (nested; vibecoder'ın frontend/ dizinini hedefle)
  --quiet            bilgi satırlarını bastır
  --force            mevcut (insan-yazımı) CLAUDE.md'yi de ez
  --version          gömülü TOOL_STAMP (experience-context/1)
  --selftest         gerçek CLI koşumlu kabul testleri (exit 0 = N/0)

Çıkış kodu: 0 = üretildi · 1 = girdi bozuk/şema-dışı (HİÇBİR dosya yazılmaz — gate) · 2 = kullanım hatası · 3 = reddedildi (mevcut non-generated CLAUDE.md — --force ile ez).`);
  process.exit(2);
}

const argv = process.argv.slice(2);
if (argv.includes('--version')) { console.log(TOOL_STAMP); process.exit(0); }
if (argv.includes('--selftest')) { selftest(); process.exit(process.exitCode || 0); }

let input, outDir, quiet = false, force = false;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--out') { outDir = argv[++i]; if (!outDir) usage(); }
  else if (a === '--quiet') quiet = true;
  else if (a === '--force') force = true;
  else if (a === '--help' || a === '-h') usage();
  else if (a.startsWith('--')) { console.error(`Bilinmeyen bayrak: ${a}`); usage(); }
  else if (input === undefined) input = a;
  else { console.error(`Fazla argüman: ${a}`); usage(); }
}
if (!input || !outDir) usage();

function fail(msg) {
  console.error(`✗ ${msg}`);
  console.error('✗ girdi bozuk/şema-dışı — HİÇBİR dosya yazılmadı (gate).');
  process.exit(1);
}

let raw;
try { raw = readFileSync(resolve(input), 'utf8'); }
catch (e) { console.error(`Girdi yolu okunamadı: ${input}`); console.error(`  ${e instanceof Error ? e.message : String(e)}`); process.exit(2); }

// --- GATE: parse + extract + render ÖNCE (bu aşamada hiçbir şey yazılmaz) ---
let md, ir;
try {
  ir = extractObligations(JSON.parse(raw));
  md = renderClaudeMd(ir, provenanceHeader(input, sha256(raw)));
} catch (e) { fail(e instanceof Error ? e.message : String(e)); }

const target = join(resolve(outDir), 'CLAUDE.md');

// --- OVERWRITE-GUARD: header'sız (insan) CLAUDE.md'yi ezme ---
if (!force && existsSync(target)) {
  let existing = '';
  try { existing = readFileSync(target, 'utf8'); } catch {}
  if (!existing.includes(HEADER_MARK)) {
    console.error(`✗ ${target} zaten var ve experience-context tarafından üretilmemiş (insan-yazımı olabilir).`);
    console.error('✗ Üzerine YAZILMADI. Korumak istemiyorsan --force ver veya başka --out seç.');
    process.exit(3);
  }
}

// --- YAZ (yalnız gate + guard geçtikten SONRA; dizin burada oluşur) ---
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, md);

if (!quiet) {
  const nScreens = ir.experiences.reduce((n, e) => n + e.screens.length, 0) + ir.sharedScreens.length;
  const allScreens = [...ir.experiences.flatMap((e) => e.screens), ...ir.sharedScreens];
  const nForms = allScreens.reduce((n, s) => n + s.forms.length, 0);
  const nActions = allScreens.reduce((n, s) => n + s.actions.length, 0);
  console.error(`✓ ${target} yazıldı · ${TOOL_STAMP} · ${nScreens} ekran / ${nForms} form / ${nActions} action · source ${input}`);
}
process.exit(0);

// ---- selftest (gerçek CLI subprocess koşumu) --------------------------------

function selftest() {
  const self = fileURLToPath(import.meta.url);
  const work = mkdtempSync(join(tmpdir(), 'exp-ctx-selftest-'));
  let pass = 0, fail = 0;
  const chk = (n, cond) => { const ok = !!cond; console.log(`  ${ok ? 'PASS' : 'FAIL'} ${n}`); ok ? pass++ : fail++; };
  // run CLI as subprocess; returns { code, stderr }
  const run = (args) => {
    try { execFileSync(process.execPath, [self, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); return { code: 0, stderr: '' }; }
    catch (e) { return { code: typeof e.status === 'number' ? e.status : 1, stderr: String(e.stderr || '') }; }
  };

  try {
    // valid fixture
    const validPath = join(work, 'valid.experience.json');
    writeFileSync(validPath, JSON.stringify({
      experiences: [{
        name: 'App',
        usesInterfaces: [{ name: 'Submit', opKind: 'command', out: { cardinality: 'single', fields: [{ name: 'id' }] } }],
        screens: [{ name: 'FormScreen', regions: [{ components: [
          { kind: 'form', submits: { op: 'Submit' }, fields: [{ name: 'code', validation: { required: true } }], rules: [] },
        ] }] }],
      }],
    }));

    // (a) valid -> CLAUDE.md yazıldı + header var
    const outA = join(work, 'a');
    const rA = run([validPath, '--out', outA, '--quiet']);
    const fileA = join(outA, 'CLAUDE.md');
    chk('(a) valid fixture exit 0', rA.code === 0);
    chk('(a) CLAUDE.md yazıldı', existsSync(fileA));
    chk('(a) header var (GENERATED by experience-context)', existsSync(fileA) && readFileSync(fileA, 'utf8').includes(HEADER_MARK));

    // (b) bozuk {} -> exit 1, CLAUDE.md YOK (gate-before-write)
    const badPath = join(work, 'bad.experience.json');
    writeFileSync(badPath, '{}');
    const outB = join(work, 'b');
    const rB = run([badPath, '--out', outB, '--quiet']);
    chk('(b) bozuk girdi exit 1', rB.code === 1);
    chk('(b) CLAUDE.md YAZILMADI', !existsSync(join(outB, 'CLAUDE.md')));

    // (c) header'sız mevcut CLAUDE.md -> exit 3, ezmez
    const outC = join(work, 'c');
    mkdirSync(outC, { recursive: true });
    const fileC = join(outC, 'CLAUDE.md');
    writeFileSync(fileC, 'insan yazdı — dokunma');
    const rC = run([validPath, '--out', outC, '--quiet']);
    chk('(c) header\'sız dosya exit 3', rC.code === 3);
    chk('(c) insan dosyası KORUNDU', readFileSync(fileC, 'utf8') === 'insan yazdı — dokunma');

    // (d) --force -> ezer
    const rD = run([validPath, '--out', outC, '--quiet', '--force']);
    chk('(d) --force exit 0', rD.code === 0);
    chk('(d) --force ile ezildi (header var)', readFileSync(fileC, 'utf8').includes(HEADER_MARK));
  } finally {
    try { rmSync(work, { recursive: true, force: true }); } catch {}
  }

  console.log(`${fail}/${pass + fail} FAIL — SELFTEST ${fail}/0 (${fail} fail)`);
  console.log(`RESULT: ${fail}/0`);
  if (fail) process.exitCode = 1;
}
