// spec-context lib — PURE (no I/O). manifest.json -> obligation IR -> CLAUDE.md text.
// Emits EXACTLY the obligations behavior-gate/gate.mjs probes (roles, validation/rule,
// invariants) plus statically-visible authz/error obligations (scopes, ownership, abac,
// throws, visibility). Deterministic: no timestamps, no Math.random — byte-stable per input.
import { createHash } from 'node:crypto';

export const TOOL_STAMP = 'spec-context/1'; // CONSTANT — bump only on renderer format change. NEVER a timestamp.

export function sha256(s) { return createHash('sha256').update(s, 'utf8').digest('hex'); }

const isRecord = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);
const str = (v, d = '') => (typeof v === 'string' ? v : d);
const strArr = (v) => (Array.isArray(v) ? v.filter((x) => typeof x === 'string') : []);
const guardText = (v) => (Array.isArray(v) ? v.filter(isRecord).map((g) => str(g.text)).filter(Boolean) : []);

export function extractObligations(m) {
  if (!isRecord(m)) throw new Error('manifest kök JSON nesnesi değil');
  if (!Array.isArray(m.operations)) throw new Error('operations dizi değil — manifest.json (emit-manifest çıktısı) mı?');
  if (!Array.isArray(m.entities)) throw new Error('entities dizi değil');
  const ops = m.operations.filter(isRecord).map((o) => ({
    id: str(o.id), module: str(o.module) || '(modülsüz)', visibility: str(o.visibility),
    roles: strArr(o.roles), scopes: strArr(o.scopes),
    ownership: typeof o.ownership === 'string' ? o.ownership : null,
    abacPresent: isRecord(o.abac), validation: guardText(o.validation),
    rule: guardText(o.rule), throws: strArr(o.throws),
  }));
  const entities = m.entities.filter(isRecord).map((e) => ({
    id: str(e.id), module: str(e.module) || '(modülsüz)',
    invariants: Array.isArray(e.invariants) ? e.invariants.filter(isRecord).map((i) => str(i.text)).filter(Boolean) : [],
  }));
  return { ops, entities };
}

export function renderClaudeMd({ ops, entities }, header) {
  const L = [header, '',
    '# Spec-Context — Backend Yükümlülükleri',
    '',
    '> Bu dosya Teknik Analiz `manifest.json`\'undan **deterministik** üretildi (spec-context). Aşağıdaki',
    '> backend operasyonlarını gerçeklerken bu yükümlülükleri **ZORUNLU** kıl. Bunlar behavior-gate\'in AYNI',
    '> manifest\'ten denetlediği kurallardır — spec değişirse ikisini **BİRLİKTE** yeniden üret. Elle DÜZENLEME.',
    ''];
  const byMod = new Map();
  for (const op of ops) { if (!byMod.has(op.module)) byMod.set(op.module, []); byMod.get(op.module).push(op); }
  for (const [mod, list] of byMod) {
    const cards = list.map(opCard).filter(Boolean);
    if (!cards.length) continue;
    L.push(`## Modül: ${mod}`, '');
    for (const c of cards) L.push(...c, '');
  }
  const entWithInv = entities.filter((e) => e.invariants.length);
  if (entWithInv.length) {
    L.push('## Entity Invariant\'ları (app state\'i HER ZAMAN sağlamalı)', '');
    for (const e of entWithInv) { L.push(`### ${e.id}`); for (const t of e.invariants) L.push(`- \`${t}\` — bu özelliği daima koru`); L.push(''); }
  }
  return L.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}
function opCard(op) {
  const authz = [], lines = [];
  if (op.roles.length) authz.push(`yalnız roller: ${op.roles.join(', ')}`);
  if (op.scopes.length) authz.push(`scope: ${op.scopes.join(', ')}`);
  if (op.ownership) authz.push(`sahiplik: ${op.ownership}`);
  if (op.abacPresent) authz.push('abac permit kuralı var (manifest\'e uy)');
  const guards = [...op.validation, ...op.rule];
  // yükümlülüğü olmayan op'u atla
  if (!authz.length && !guards.length && !op.throws.length) return null;
  lines.push(`### ${op.id}${op.visibility ? ` (${op.visibility})` : ''}`);
  if (authz.length) lines.push(`- **Yetki (ZORUNLU zorla):** ${authz.join(' · ')}`);
  if (guards.length) { lines.push('- **Girdi guard\'ları (ihlal → ZORUNLU reddet):**'); for (const g of guards) lines.push(`  - \`${g}\``); }
  if (op.throws.length) lines.push(`- **Fırlatılabilir hatalar:** ${op.throws.map((t) => `\`${t}\``).join(' · ')}`);
  return lines;
}

export function provenanceHeader(srcPath, hash) {
  return `<!-- GENERATED by spec-context — DO NOT EDIT · source: ${srcPath} · sha256:${hash} · ${TOOL_STAMP} -->`;
}

function selftest() {
  let p = 0, f = 0; const chk = (n, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); console.log(`  ${ok ? 'PASS' : 'FAIL'} ${n}`); ok ? p++ : f++; };
  const m = { operations: [
    { id: 'IssueGiftCard', module: 'GC', visibility: 'exposed', roles: ['System'], scopes: [], abac: null, validation: [{ text: 'amount > 0' }], rule: [], throws: ['budgetExceeded'] },
    { id: 'Ping', module: 'GC', roles: [], validation: [], rule: [], throws: [] } ], // yükümlülüksüz → atlanmalı
    entities: [{ id: 'Ledger', module: 'GC', invariants: [{ text: 'sum of entries.amount = total' }] }] };
  const ir = extractObligations(m);
  chk('extract op count', ir.ops.length, 2);
  chk('extract roles', ir.ops[0].roles, ['System']);
  chk('extract validation text', ir.ops[0].validation, ['amount > 0']);
  chk('extract invariant', ir.entities[0].invariants, ['sum of entries.amount = total']);
  const md = renderClaudeMd(ir, provenanceHeader('x/manifest.json', 'abc'));
  chk('render has issue op', md.includes('### IssueGiftCard'), true);
  chk('render SKIPS obligationless op', md.includes('### Ping'), false);           // negatif
  chk('render imperative reject', md.includes('ZORUNLU reddet'), true);
  chk('render invariant section', md.includes('sum of entries.amount = total'), true);
  chk('render NO timestamp/manifest-dump', /serving|pagination|builtAt|\d{4}-\d\d-\d\dT/.test(md), false); // negatif: dökme/timestamp yok
  chk('header no timestamp', /\d{4}-\d\d-\d\dT/.test(provenanceHeader('a', 'b')), false);
  // negatif: bozuk manifest throw
  let threw = false; try { extractObligations({ operations: 'x' }); } catch { threw = true; }
  chk('extract throws on malformed', threw, true);
  console.log(`SELFTEST: ${p} pass, ${f} fail`); if (f) process.exitCode = 1;
}
if (process.argv.includes('--selftest')) selftest();
