#!/usr/bin/env node
// spec-context CLI — manifest.json -> <out>/CLAUDE.md (deterministik). Kod üretmez, app çalıştırmaz.
// Bozuk/şema-dışı girdi -> exit 1, HİÇBİR ŞEY yazmaz (gate). report-tech.mjs CLI emsali.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { extractObligations, renderClaudeMd, provenanceHeader, sha256, TOOL_STAMP } from './lib.mjs';

function usage() {
  console.error(`Kullanım: node spec-context.mjs <manifest.json> --out <dizin> [--quiet]
          node spec-context.mjs --version

  <manifest.json>   Teknik Analiz emit-manifest çıktısı (0-error koşunun ürünü)
  --out <dizin>     CLAUDE.md yazılacak dizin (nested; vibecoder'ın backend/ dizinini hedefle)
  --quiet           bilgi satırlarını bastır
  --force           mevcut (insan-yazımı) CLAUDE.md'yi de ez
  --version         gömülü TOOL_STAMP

Çıkış kodu: 0 = üretildi · 1 = girdi bozuk/şema-dışı (HİÇBİR dosya yazılmaz — gate) · 2 = kullanım hatası · 3 = reddedildi (mevcut non-generated CLAUDE.md — --force ile ez).`);
  process.exit(2);
}

const argv = process.argv.slice(2);
if (argv.includes('--version')) { console.log(TOOL_STAMP); process.exit(0); }
let input, outDir, quiet = false, force = false;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === '--out') { outDir = argv[++i]; if (!outDir) usage(); }
  else if (a === '--quiet') quiet = true;
  else if (a === '--force') force = true;
  else if (a === '--help' || a === '-h') usage();
  else if (a.startsWith('--')) { console.error(`Bilinmeyen bayrak: ${a}`); usage(); }
  else if (input === undefined) input = a;
  else { console.error(`Fazla argüman: ${a}`); usage(); }
}
if (!input || !outDir) usage();

function fail(msg) {
  console.error(`✗ ${msg}`);
  console.error('✗ girdi bozuk/şema-dışı — HİÇBİR dosya yazılmadı (gate).');
  process.exit(1);
}

let raw;
try { raw = readFileSync(resolve(input), 'utf8'); }
catch (e) { console.error(`Girdi yolu okunamadı: ${input}`); console.error(`  ${e instanceof Error ? e.message : String(e)}`); process.exit(2); }

let md;
try {
  const ir = extractObligations(JSON.parse(raw));
  md = renderClaudeMd(ir, provenanceHeader(input, sha256(raw)));
} catch (e) { fail(e instanceof Error ? e.message : String(e)); }

const target = join(resolve(outDir), 'CLAUDE.md');
if (!force && existsSync(target)) {
  let existing = '';
  try { existing = readFileSync(target, 'utf8'); } catch {}
  if (!existing.includes('GENERATED by spec-context')) {
    console.error(`✗ ${target} zaten var ve spec-context tarafından üretilmemiş (insan-yazımı olabilir).`);
    console.error('✗ Üzerine YAZILMADI. Korumak istemiyorsan --force ver veya başka --out seç.');
    process.exit(3);
  }
}
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, md);
if (!quiet) console.error(`✓ ${target} yazıldı · ${TOOL_STAMP} · source ${input}`);
process.exit(0);
